image: maven:3-eclipse-temurin-21

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

stages:
  - test
  - deploy

cache:
  paths:
    - .m2/repository
    - target

test:
  stage: test
  script:
    - 'echo $MAVEN_SETTINGS_XML >> ci_settings.xml'
    - 'mvn $MAVEN_CLI_OPTS test -U --settings ci_settings.xml'

deploy:
  stage: deploy
  script:
    - 'echo $MAVEN_SETTINGS_XML >> ci_settings.xml'
    - 'mvn $MAVEN_CLI_OPTS deploy -U --settings ci_settings.xml'
  only:
    - main