image: maven:3-eclipse-temurin-21

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - test
  - deploy

cache:
  paths:
    - .m2/repository
    - target

test:
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dusername=$NEXUS_USERNAME -Dpassword=$NEXUS_PASSWORD
  only:
    - main